name: http-request-workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: the current branch
        required: true
        type: string
      PR:
        required: true
        description: the current PR
        type: string

jobs:
  automatic:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: Success!
        pr_number: ${{ inputs.PR }}
        comment_tag: workflow_validation
