name: http-request-workflow-2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: the current branch
        required: true
        type: string
      PR:
        required: true
        description: the current PR
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
        - name: start
          shell: bash
          run: |
            if [ ${{ matrix.containers }} % 2 == 0 ]; then
              exit 0
            else
              exit 1
            fi

  check_test_results:
    needs: [run-tests]
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Comment success
        if: ${{ job.status }}" == "success"
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "✅ Merge - Successed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          pr_number: ${{ inputs.PR }}
          comment_tag: auto_merge

      - name: Comment failed
        if: ${{ job.status }}" != "success"
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "❌ Merge - Failed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          pr_number: ${{ inputs.PR }}
          comment_tag: auto_merge