name: http-request-workflow-2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: the current branch
        required: true
        type: string
      PR:
        required: true
        description: the current PR
        type: string
      result:
        required: true
        description: the step result
        type: string

jobs:
  automatic:
    permissions: write-all
    runs-on: ubuntu-latest  
    steps:
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: ${{ inputs.result }} \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        pr_number: ${{ inputs.PR }}
        comment_tag: auto_merge
