name: http-request-workflow-2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: the current branch
        required: true
        type: string
      PR:
        required: true
        description: the current PR
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    outputs:
        results: ${{ steps.finish.outputs.result }}
    steps:
        - name: start
          id: start
          shell: bash
          run: exit ${{ matrix.containers }}

        - name: get output
          id: finish
          if: always()
          shell: bash
          run: echo "result=${{ job.status }}" >> "$GITHUB_OUTPUT"

  check_test_results:
    needs: [run-tests]
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
        - name: Echo outputs
          shell: bash
          run: echo ${{ toJSON(needs.jobs.run-tests.strategy) }}
      # - name: Comment success
      #   if: ${{ job.status }}" == "success"
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     message: "✅ Merge - Successed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     pr_number: ${{ inputs.PR }}
      #     comment_tag: auto_merge

      # - name: Comment failed
      #   if: ${{ job.status }}" != "success"
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     message: "❌ Merge - Failed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     pr_number: ${{ inputs.PR }}
      #     comment_tag: auto_merge