name: Main action

on:
  pull_request:
    branches: [master]
    # types: [labeled]

env:
  BRANCH: ${{ github.ref }}

jobs:
  define-what-to-run:
    runs-on: ubuntu-latest
      
    steps:
      - name: Call http action
        # if: github.event.label.name == 'Em revisão'
        run: |
          echo "Chamando a action"          
          curl --request POST \
            --url 'https://api.github.com/repos/calvesrodrig/github-flow/actions/workflows/51755224/dispatches' \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --data '{"ref":"${{ github.ref }}","inputs":{"branch": "${{ github.ref }}","PR": "${{ github.event.number }}"}'