name: Main action

on:
  pull_request:
    branches: [master]
    types: [labeled]

env:
  BRANCH: ${{ github.ref }}

jobs:
  run-tests:
    if: github.event.label.name == 'Em revisão'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Call http action
        shell: bash
        run: |
          echo "Chamando a action"          
          curl --request POST \
            --url 'https://api.github.com/repos/calvesrodrig/github-flow/actions/workflows/51755224/dispatches' \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --data '{"ref":"master","inputs":{"branch": "${{ github.ref }}","PR": "${{ github.event.number }}", "result": "✅ Tests - Success \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'

  auto-merge:
    if: github.event.label.name == 'Alpha Cruzado'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Call http action again
        shell: bash
        run: |
          echo "Chamando a action"          
          curl --request POST \
            --url 'https://api.github.com/repos/calvesrodrig/github-flow/actions/workflows/51897563/dispatches' \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --data '{"ref":"master","inputs":{"branch": "${{ github.ref }}","PR": "${{ github.event.number }}", "result": "❌ Merge - Failed \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'